/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 120.c                                                 *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      90                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 90                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: G:\Users\Administrator\Desktop\temporary\NAVTEX\NAVTEX1.3\120.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font120;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font120_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0041[357] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,__XXXXXX,XXXXXX__,________,________,________,
  ________,________,_XXXXXXX,XXXXXXX_,________,________,________,
  ________,________,_XXXXXXX,XXXXXXX_,________,________,________,
  ________,________,_XXXXXXX,XXXXXXX_,________,________,________,
  ________,________,XXXXXXXX,XXXXXXXX,________,________,________,
  ________,________,XXXXXXXX,XXXXXXXX,________,________,________,
  ________,________,XXXXXXXX,XXXXXXXX,________,________,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,X_______,________,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,X_______,________,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,XX______,________,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XX______,________,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XX______,________,________,
  ________,______XX,XXXXXXX_,_XXXXXXX,XXX_____,________,________,
  ________,_____XXX,XXXXXXX_,_XXXXXXX,XXX_____,________,________,
  ________,_____XXX,XXXXXXX_,_XXXXXXX,XXX_____,________,________,
  ________,_____XXX,XXXXXX__,__XXXXXX,XXXX____,________,________,
  ________,____XXXX,XXXXXX__,__XXXXXX,XXXX____,________,________,
  ________,____XXXX,XXXXXX__,__XXXXXX,XXXXX___,________,________,
  ________,___XXXXX,XXXXXX__,___XXXXX,XXXXX___,________,________,
  ________,___XXXXX,XXXXX___,___XXXXX,XXXXX___,________,________,
  ________,___XXXXX,XXXXX___,___XXXXX,XXXXXX__,________,________,
  ________,__XXXXXX,XXXXX___,____XXXX,XXXXXX__,________,________,
  ________,__XXXXXX,XXXX____,____XXXX,XXXXXX__,________,________,
  ________,__XXXXXX,XXXX____,____XXXX,XXXXXXX_,________,________,
  ________,_XXXXXXX,XXXX____,_____XXX,XXXXXXX_,________,________,
  ________,_XXXXXXX,XXX_____,_____XXX,XXXXXXXX,________,________,
  ________,_XXXXXXX,XXX_____,_____XXX,XXXXXXXX,________,________,
  ________,XXXXXXXX,XXX_____,______XX,XXXXXXXX,________,________,
  ________,XXXXXXXX,XX______,______XX,XXXXXXXX,X_______,________,
  ________,XXXXXXXX,XX______,______XX,XXXXXXXX,X_______,________,
  _______X,XXXXXXXX,XX______,_______X,XXXXXXXX,X_______,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ____XXXX,XXXXXXX_,________,________,__XXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXX_,________,________,__XXXXXX,XXXXX___,________,
  ___XXXXX,XXXXXXX_,________,________,__XXXXXX,XXXXX___,________,
  ___XXXXX,XXXXXX__,________,________,___XXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXX__,________,________,___XXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXX__,________,________,___XXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXX___,________,________,____XXXX,XXXXXXX_,________,
  __XXXXXX,XXXXX___,________,________,____XXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXX___,________,________,____XXXX,XXXXXXXX,________,
  _XXXXXXX,XXXX____,________,________,_____XXX,XXXXXXXX,________,
  _XXXXXXX,XXXX____,________,________,_____XXX,XXXXXXXX,________,
  XXXXXXXX,XXXX____,________,________,_____XXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0043[265] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,________,_____XXX,XXXXXXXX,XX______,
  ________,________,_XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_______X,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ______XX,XXXXXXXX,XXXXXXX_,________,XXXXXXX_,
  _____XXX,XXXXXXXX,XXXX____,________,____XXX_,
  ____XXXX,XXXXXXXX,XX______,________,______X_,
  ____XXXX,XXXXXXXX,X_______,________,________,
  ___XXXXX,XXXXXXXX,________,________,________,
  ___XXXXX,XXXXXXX_,________,________,________,
  __XXXXXX,XXXXXX__,________,________,________,
  __XXXXXX,XXXXXX__,________,________,________,
  __XXXXXX,XXXXX___,________,________,________,
  _XXXXXXX,XXXXX___,________,________,________,
  _XXXXXXX,XXXX____,________,________,________,
  _XXXXXXX,XXXX____,________,________,________,
  _XXXXXXX,XXXX____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXX_____,________,________,________,
  XXXXXXXX,XXXX____,________,________,________,
  XXXXXXXX,XXXX____,________,________,________,
  _XXXXXXX,XXXX____,________,________,________,
  _XXXXXXX,XXXXX___,________,________,________,
  _XXXXXXX,XXXXX___,________,________,________,
  __XXXXXX,XXXXXX__,________,________,________,
  __XXXXXX,XXXXXXX_,________,________,________,
  __XXXXXX,XXXXXXX_,________,________,________,
  ___XXXXX,XXXXXXXX,________,________,________,
  ___XXXXX,XXXXXXXX,XX______,________,______X_,
  ____XXXX,XXXXXXXX,XXX_____,________,____XXX_,
  _____XXX,XXXXXXXX,XXXXXX__,________,XXXXXXX_,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,_______X,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,________,___XXXXX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0045[204] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0049[153] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font120_004E[306] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXXXXXX,XXXX____,________,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,________,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,________,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,________,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXX_,________,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXX_,________,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,________,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,X_______,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,X_______,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XX______,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXX_____,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXX_____,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXX____,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXX____,________,___XXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,________,___XXXXX,XXXXX___,
  XXXXXXXX,XX_XXXXX,XXXXXX__,________,___XXXXX,XXXXX___,
  XXXXXXXX,XX__XXXX,XXXXXX__,________,___XXXXX,XXXXX___,
  XXXXXXXX,XX__XXXX,XXXXXXX_,________,___XXXXX,XXXXX___,
  XXXXXXXX,XX___XXX,XXXXXXXX,________,___XXXXX,XXXXX___,
  XXXXXXXX,XX___XXX,XXXXXXXX,________,___XXXXX,XXXXX___,
  XXXXXXXX,XX____XX,XXXXXXXX,X_______,___XXXXX,XXXXX___,
  XXXXXXXX,XX_____X,XXXXXXXX,XX______,___XXXXX,XXXXX___,
  XXXXXXXX,XX_____X,XXXXXXXX,XX______,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,XXXXXXXX,XXX_____,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,_XXXXXXX,XXXX____,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,_XXXXXXX,XXXX____,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,__XXXXXX,XXXXX___,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,___XXXXX,XXXXX___,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,___XXXXX,XXXXXX__,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,____XXXX,XXXXXXX_,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,_____XXX,XXXXXXX_,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,_____XXX,XXXXXXXX,___XXXXX,XXXXX___,
  XXXXXXXX,XX______,______XX,XXXXXXXX,X__XXXXX,XXXXX___,
  XXXXXXXX,XX______,_______X,XXXXXXXX,X__XXXXX,XXXXX___,
  XXXXXXXX,XX______,_______X,XXXXXXXX,XX_XXXXX,XXXXX___,
  XXXXXXXX,XX______,________,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,_XXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,_XXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,__XXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,__XXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,___XXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,____XXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,____XXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,_____XXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,______XX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,______XX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,_______X,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,________,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,________,XXXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,________,_XXXXXXX,XXXXX___,
  XXXXXXXX,XX______,________,________,__XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0052[306] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXX_____,____XXXX,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXX_____,_______X,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXX_____,________,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,_XXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,_XXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,_XXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,_XXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,_XXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,_XXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXX_____,________,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXX_____,_______X,XXXXXXXX,XX______,________,
  XXXXXXXX,XXX_____,______XX,XXXXXXXX,XX______,________,
  XXXXXXXX,XXX_____,____XXXX,XXXXXXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,________,
  XXXXXXXX,XXX_____,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXX_____,__XXXXXX,XXXXXX__,________,________,
  XXXXXXXX,XXX_____,___XXXXX,XXXXXXX_,________,________,
  XXXXXXXX,XXX_____,____XXXX,XXXXXXXX,________,________,
  XXXXXXXX,XXX_____,____XXXX,XXXXXXXX,________,________,
  XXXXXXXX,XXX_____,_____XXX,XXXXXXXX,X_______,________,
  XXXXXXXX,XXX_____,_____XXX,XXXXXXXX,X_______,________,
  XXXXXXXX,XXX_____,______XX,XXXXXXXX,XX______,________,
  XXXXXXXX,XXX_____,_______X,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXX_____,_______X,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXX_____,________,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXX_____,________,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXX_____,________,_XXXXXXX,XXXXX___,________,
  XXXXXXXX,XXX_____,________,__XXXXXX,XXXXXX__,________,
  XXXXXXXX,XXX_____,________,__XXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXX_____,________,___XXXXX,XXXXXXX_,________,
  XXXXXXXX,XXX_____,________,___XXXXX,XXXXXXXX,________,
  XXXXXXXX,XXX_____,________,____XXXX,XXXXXXXX,________,
  XXXXXXXX,XXX_____,________,_____XXX,XXXXXXXX,X_______,
  XXXXXXXX,XXX_____,________,_____XXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0054[255] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0056[306] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXXXXXX,XXXX____,________,________,____XXXX,XXXXXXXX,
  _XXXXXXX,XXXX____,________,________,____XXXX,XXXXXXX_,
  _XXXXXXX,XXXXX___,________,________,____XXXX,XXXXXXX_,
  _XXXXXXX,XXXXX___,________,________,___XXXXX,XXXXXXX_,
  __XXXXXX,XXXXX___,________,________,___XXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,________,________,___XXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXX__,
  ___XXXXX,XXXXXX__,________,________,__XXXXXX,XXXXX___,
  ___XXXXX,XXXXXX__,________,________,__XXXXXX,XXXXX___,
  ___XXXXX,XXXXXXX_,________,________,__XXXXXX,XXXXX___,
  ____XXXX,XXXXXXX_,________,________,_XXXXXXX,XXXX____,
  ____XXXX,XXXXXXX_,________,________,_XXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,________,________,_XXXXXXX,XXXX____,
  _____XXX,XXXXXXXX,________,________,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,________,________,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,X_______,________,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,X_______,_______X,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,X_______,_______X,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,XX______,_______X,XXXXXXXX,XX______,
  _______X,XXXXXXXX,XX______,______XX,XXXXXXXX,X_______,
  _______X,XXXXXXXX,XX______,______XX,XXXXXXXX,X_______,
  _______X,XXXXXXXX,XX______,______XX,XXXXXXXX,________,
  ________,XXXXXXXX,XXX_____,______XX,XXXXXXXX,________,
  ________,XXXXXXXX,XXX_____,_____XXX,XXXXXXXX,________,
  ________,XXXXXXXX,XXX_____,_____XXX,XXXXXXX_,________,
  ________,_XXXXXXX,XXXX____,_____XXX,XXXXXXX_,________,
  ________,_XXXXXXX,XXXX____,____XXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXX____,____XXXX,XXXXXX__,________,
  ________,__XXXXXX,XXXXX___,____XXXX,XXXXXX__,________,
  ________,__XXXXXX,XXXXX___,___XXXXX,XXXXXX__,________,
  ________,___XXXXX,XXXXX___,___XXXXX,XXXXX___,________,
  ________,___XXXXX,XXXXXX__,___XXXXX,XXXXX___,________,
  ________,___XXXXX,XXXXXX__,__XXXXXX,XXXXX___,________,
  ________,____XXXX,XXXXXX__,__XXXXXX,XXXX____,________,
  ________,____XXXX,XXXXXXX_,__XXXXXX,XXXX____,________,
  ________,____XXXX,XXXXXXX_,_XXXXXXX,XXXX____,________,
  ________,_____XXX,XXXXXXX_,_XXXXXXX,XXX_____,________,
  ________,_____XXX,XXXXXXX_,_XXXXXXX,XXX_____,________,
  ________,_____XXX,XXXXXXXX,_XXXXXXX,XX______,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,________,________,
  ________,________,XXXXXXXX,XXXXXXXX,________,________,
  ________,________,XXXXXXXX,XXXXXXXX,________,________,
  ________,________,XXXXXXXX,XXXXXXX_,________,________,
  ________,________,_XXXXXXX,XXXXXXX_,________,________,
  ________,________,_XXXXXXX,XXXXXXX_,________,________,
  ________,________,_XXXXXXX,XXXXXX__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0058[306] = { /* code 0058, LATIN CAPITAL LETTER X */
  _XXXXXXX,XXXXXXX_,________,________,__XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,XX______,______XX,XXXXXXXX,XX______,
  _____XXX,XXXXXXXX,XX______,______XX,XXXXXXXX,X_______,
  ______XX,XXXXXXXX,XX______,_____XXX,XXXXXXXX,X_______,
  _______X,XXXXXXXX,XXX_____,_____XXX,XXXXXXXX,________,
  _______X,XXXXXXXX,XXX_____,____XXXX,XXXXXXXX,________,
  ________,XXXXXXXX,XXXX____,___XXXXX,XXXXXXX_,________,
  ________,XXXXXXXX,XXXX____,___XXXXX,XXXXXX__,________,
  ________,_XXXXXXX,XXXXX___,__XXXXXX,XXXXXX__,________,
  ________,__XXXXXX,XXXXX___,__XXXXXX,XXXXX___,________,
  ________,__XXXXXX,XXXXXX__,_XXXXXXX,XXXX____,________,
  ________,___XXXXX,XXXXXX__,_XXXXXXX,XXXX____,________,
  ________,___XXXXX,XXXXXXX_,XXXXXXXX,XXX_____,________,
  ________,____XXXX,XXXXXXX_,XXXXXXXX,XXX_____,________,
  ________,_____XXX,XXXXXXX_,XXXXXXXX,XX______,________,
  ________,_____XXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,________,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,________,________,
  ________,________,XXXXXXXX,XXXXXXX_,________,________,
  ________,________,XXXXXXXX,XXXXXXX_,________,________,
  ________,_______X,XXXXXXXX,XXXXXXX_,________,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,________,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,________,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,_____XXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,____XXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,____XXXX,XXXXXXX_,XXXXXXXX,XXX_____,________,
  ________,___XXXXX,XXXXXX__,XXXXXXXX,XXX_____,________,
  ________,__XXXXXX,XXXXXX__,XXXXXXXX,XXXX____,________,
  ________,__XXXXXX,XXXXX___,_XXXXXXX,XXXXX___,________,
  ________,_XXXXXXX,XXXXX___,_XXXXXXX,XXXXX___,________,
  ________,_XXXXXXX,XXXX____,__XXXXXX,XXXXXX__,________,
  ________,XXXXXXXX,XXXX____,___XXXXX,XXXXXX__,________,
  _______X,XXXXXXXX,XXX_____,___XXXXX,XXXXXXX_,________,
  _______X,XXXXXXXX,XXX_____,____XXXX,XXXXXXXX,________,
  ______XX,XXXXXXXX,XX______,____XXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,X_______,_____XXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,X_______,_____XXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,________,______XX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,________,______XX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXX_,________,_______X,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXX_,________,_______X,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,________,________,_XXXXXXX,XXXXXX__};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Font120_CharInfo[10] = {
   {   1,   1,   0,  71,  20, acGUI_Font120_0020 } /* code 0020, SPACE */
  ,{  49,  51,   1,  20,  50, acGUI_Font120_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  39,  53,   3,  19,  45, acGUI_Font120_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  30,  51,   6,  20,  38, acGUI_Font120_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  19,  51,   2,  20,  22, acGUI_Font120_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  45,  51,   6,  20,  57, acGUI_Font120_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  42,  51,   6,  20,  47, acGUI_Font120_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  40,  51,   1,  20,  42, acGUI_Font120_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  48,  51,   0,  20,  48, acGUI_Font120_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  46,  51,   0,  20,  47, acGUI_Font120_0058 } /* code 0058, LATIN CAPITAL LETTER X */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop10 = {
   0x0058 /* first character */
  ,0x0058 /* last character  */
  ,&GUI_Font120_CharInfo[  9] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop9 = {
   0x0056 /* first character */
  ,0x0056 /* last character  */
  ,&GUI_Font120_CharInfo[  8] /* address of first character */
  ,&GUI_Font120_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop8 = {
   0x0054 /* first character */
  ,0x0054 /* last character  */
  ,&GUI_Font120_CharInfo[  7] /* address of first character */
  ,&GUI_Font120_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop7 = {
   0x0052 /* first character */
  ,0x0052 /* last character  */
  ,&GUI_Font120_CharInfo[  6] /* address of first character */
  ,&GUI_Font120_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop6 = {
   0x004E /* first character */
  ,0x004E /* last character  */
  ,&GUI_Font120_CharInfo[  5] /* address of first character */
  ,&GUI_Font120_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop5 = {
   0x0049 /* first character */
  ,0x0049 /* last character  */
  ,&GUI_Font120_CharInfo[  4] /* address of first character */
  ,&GUI_Font120_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop4 = {
   0x0045 /* first character */
  ,0x0045 /* last character  */
  ,&GUI_Font120_CharInfo[  3] /* address of first character */
  ,&GUI_Font120_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop3 = {
   0x0043 /* first character */
  ,0x0043 /* last character  */
  ,&GUI_Font120_CharInfo[  2] /* address of first character */
  ,&GUI_Font120_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop2 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_Font120_CharInfo[  1] /* address of first character */
  ,&GUI_Font120_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Font120_CharInfo[  0] /* address of first character */
  ,&GUI_Font120_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font120 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,90 /* height of font  */
  ,90 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font120_Prop1}
  ,71 /* Baseline */
  ,38 /* Height of lowercase characters */
  ,51 /* Height of capital characters */
};

